on:
  workflow_dispatch:
jobs:
  test_job:
    name: Echo Test Secret
    runs-on: ubuntu-22.04
    env:
      CODESPACE_TEST_SECRET: ${{ secrets.TEST_SECRET }}
      REPO_TEST_SECRET: ${{ secrets.REPO_TEST_SECRET }}
    steps:
      - name: Echo Test Secret
        run: echo "Codespace Secret = $CODESPACE_TEST_SECRET \n Repo Secret = $REPO_TEST_SECRET"
